name: 01 - Building blocks
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps: 
            - name: Say hello
              run: echo "Started job"
    echo-goodbye:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Failed
    #           run: |
    #                 echo "Failed step failed"
    #                 exit 1
        runs-on: ubuntu-latest
        steps:
            - name: Say goodbye
              run: echo "Goodbye"
